include Makefile.common
OBJS = $(OBJS) windows/drawing_win.o windows/texture_win.o windows/input_win.o windows/pvr_win.o \
windows/framerateselect_win.o windows/file_win.o windows/math_win.o windows/system_win.o windows/log_win.o \
windows/soundeffect_win.o windows/sound_win.o windows/memoryhandler_win.o windows/romdisk_win.o \
windows/screeneffect_win.o windows/logoscreen_win.o

all: $(TARGET)

TARI_PATH = .
include Makefile.commonweb

clean_library:
	-del *.o
	-cd windows && del *.o
	-rmdir /s /q bin
	
libtari.a: $(OBJS)
	emar rcs $@ $(OBJS)
	-mkdir bin
	move $@ bin\$@
	
	